dhanani_ria_ezu/courseinfo/urls.py
from django.contrib import admin
from django.urls import path
from courseinfo.views import (
    InstructorList, SectionList, CourseList, SemesterList, StudentList, RegistrationList, InstructorDetail,
    SectionDetail, CourseDetail, SemesterDetail, StudentDetail, RegistrationDetail, InstructorCreate, SectionCreate,
    CourseCreate, StudentCreate, RegistrationCreate, SemesterCreate, InstructorUpdate, SectionUpdate, CourseUpdate,
    SemesterUpdate, StudentUpdate, RegistrationUpdate, RegistrationDelete, InstructorDelete, SectionDelete, CourseDelete,
    SemesterDelete, StudentDelete
)

urlpatterns = [
    path('instructor/',
         InstructorList.as_view(),
         name='courseinfo_instructor_list_urlpattern'),

    path('instructor/<int:pk>/',
         InstructorDetail.as_view(),
         name='courseinfo_instructor_detail_list_urlpattern'),

    path('instructor/create/',
         InstructorCreate.as_view(),
         name='courseinfo_instructor_create_urlpattern'),

    path('instructor/<int:pk>/update',
         InstructorUpdate.as_view(),
         name='courseinfo_instructor_update_urlpattern'),

    path('instructor/<int:pk>/delete',
         InstructorDelete.as_view(),
         name='courseinfo_instructor_delete_urlpattern'),

    path('section/',
         SectionList.as_view(),
         name='courseinfo_section_list_urlpattern'),

    path('section/<int:pk>/',
         SectionDetail.as_view(),
         name='courseinfo_section_detail_list_urlpattern'),

    path('section/create/',
         SectionCreate.as_view(),
         name='courseinfo_section_create_urlpattern'),

    path('section/<int:pk>/update',
         SectionUpdate.as_view(),
         name='courseinfo_section_update_urlpattern'),

    path('section/<int:pk>/delete',
         SectionDelete.as_view(),
         name='courseinfo_section_delete_urlpattern'),

    path('course/',
         CourseList.as_view(),
         name='courseinfo_course_list_urlpattern'),

    path('course/<int:pk>/',
         CourseDetail.as_view(),
         name='courseinfo_course_detail_list_urlpattern'),

    path('course/create/',
         CourseCreate.as_view(),
         name='courseinfo_course_create_urlpattern'),

    path('course/<int:pk>/update',
            CourseUpdate.as_view(),
         name='courseinfo_course_update_urlpattern'),

    path('course/<int:pk>/delete',
         CourseDelete.as_view(),
         name='courseinfo_course_delete_urlpattern'),

    path('semester/',
         SemesterList.as_view(),
         name='courseinfo_semester_list_urlpattern'),

    path('semester/<int:pk>/',
             SemesterDetail.as_view(),
             name='courseinfo_semester_detail_list_urlpattern'),

    path('semester/create/',
         SemesterCreate.as_view(),
         name='courseinfo_semester_create_urlpattern'),

    path('semester/<int:pk>/update',
         SemesterUpdate.as_view(),
         name='courseinfo_semester_update_urlpattern'),

    path('semester/<int:pk>/delete',
         SemesterDelete.as_view(),
         name='courseinfo_semester_delete_urlpattern'),

    path('student/',
         StudentList.as_view(),
         name='courseinfo_student_list_urlpattern'),

    path('student/<int:pk>/',
             StudentDetail.as_view(),
             name='courseinfo_student_detail_list_urlpattern'),

    path('student/create/',
         StudentCreate.as_view(),
         name='courseinfo_student_create_urlpattern'),

    path('student/<int:pk>/update',
         StudentUpdate.as_view(),
         name='courseinfo_student_update_urlpattern'),

    path('student/<int:pk>/delete',
         StudentDelete.as_view(),
         name='courseinfo_student_delete_urlpattern'),

    path('registration/',
         RegistrationList.as_view(),
         name='courseinfo_registration_list_urlpattern'),

    path('registration/<int:pk>/',
             RegistrationDetail.as_view(),
             name='courseinfo_registration_detail_list_urlpattern'),

    path('registration/create/',
         RegistrationCreate.as_view(),
         name='courseinfo_registration_create_urlpattern'),

    path('registration/<int:pk>/update',
         RegistrationUpdate.as_view(),
         name='courseinfo_registration_update_urlpattern'),

    path('registration/<int:pk>/delete',
         RegistrationDelete.as_view(),
         name='courseinfo_registration_delete_urlpattern'),

]

dhanani_ria_ezu/courseinfo/models.py
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse


class Period(models.Model):
    period_id = models.AutoField(primary_key=True)
    period_sequence = models.IntegerField(unique=True)
    period_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return '%s' % self.period_name

    class Meta:
        ordering = ['period_sequence']


class Year(models.Model):
    year_id = models.AutoField(primary_key=True)
    year = models.IntegerField(unique=True)

    def __str__(self):
        return '%s' % self.year

    class Meta:
        ordering = ['year']


class Semester(models.Model):
    semester_id = models.AutoField(primary_key=True)
    year = models.ForeignKey(Year, related_name='semesters', on_delete=models.PROTECT)
    period = models.ForeignKey(Period, related_name='semesters', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s' % (self.year.year, self.period.period_name)

    def get_absolute_url(self):
        return reverse('courseinfo_semester_detail_list_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_semester_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_semester_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['year__year', 'period__period_sequence']
        constraints = [
            UniqueConstraint(fields=['year', 'period'], name='unique_semester')
        ]


class Course(models.Model):
    course_id = models.AutoField(primary_key=True)
    course_number = models.CharField(max_length=20)
    course_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s - %s' % (self.course_number, self.course_name)

    def get_absolute_url(self):
        return reverse('courseinfo_course_detail_list_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_course_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_course_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['course_number', 'course_name']
        constraints = [
            UniqueConstraint(fields=['course_number', 'course_name'], name='unique_course')
        ]


class Instructor(models.Model):
    instructor_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    disambiguator = models.CharField(max_length=45, blank=True, default='')

    def __str__(self):
        result = ''
        if self.disambiguator == '':
            result = '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.disambiguator)
        return result

    def get_absolute_url(self):
        return reverse('courseinfo_instructor_detail_list_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_instructor_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_instructor_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name', 'disambiguator']
        constraints = [
            UniqueConstraint(fields=['last_name', 'first_name', 'disambiguator'],
                             name='unique_instructor')
        ]



class Student(models.Model):
    student_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    disambiguator = models.CharField(max_length=45, blank=True, default='')

    def __str__(self):
        result = ''
        if self.disambiguator == '':
            result = '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.disambiguator)
        return result

    def get_absolute_url(self):
        return reverse('courseinfo_student_detail_list_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_student_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_student_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name', 'disambiguator']
        constraints = [
            UniqueConstraint(fields=['last_name', 'first_name', 'disambiguator'],
                             name='unique_student')
        ]


class Section(models.Model):
    section_id = models.AutoField(primary_key=True)
    section_name = models.CharField(max_length=20)
    semester = models.ForeignKey(Semester, related_name='sections', on_delete=models.PROTECT)
    course = models.ForeignKey(Course, related_name='sections', on_delete=models.PROTECT)
    instructor = models.ForeignKey(Instructor, related_name='sections', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s (%s)' % (self.course.course_number, self.section_name, self.semester.__str__())

    def get_absolute_url(self):
        return reverse('courseinfo_section_detail_list_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_section_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_section_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['course', 'section_name', 'semester']
        constraints = [
            UniqueConstraint(fields=['semester', 'course', 'section_name'], name='unique_section')
        ]


class Registration(models.Model):
    registration_id = models.AutoField(primary_key=True)
    student = models.ForeignKey(Student, related_name='registrations', on_delete=models.PROTECT)
    section = models.ForeignKey(Section, related_name='registrations', on_delete=models.PROTECT)

    def __str__(self):
        return '%s / %s' % (self.section, self.student)

    def get_absolute_url(self):
        return reverse('courseinfo_registration_detail_list_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('courseinfo_registration_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('courseinfo_registration_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['section', 'student']
        constraints = [
            UniqueConstraint(fields=['section', 'student'],
                             name='unique_registration')
        ]

dhanani_ria_ezu/courseinfo/forms.py
from django import forms

from courseinfo.models import Instructor, Section, Course, Student, Registration, Semester


class InstructorForm(forms.ModelForm):
    class Meta:
        model = Instructor
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()

    def clean_disambiguator(self):
        if len(self.cleaned_data['disambiguator']) == 0:
            result = self.cleaned_data['disambiguator']
        else:
            result = self.cleaned_data['disambiguator'].strip()

        return result


class SectionForm(forms.ModelForm):
    class Meta:
        model = Section
        fields = '__all__'

    def clean_section_name(self):
        return self.cleaned_data['section_name'].strip()


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

    def clean_course_name(self):
        return self.cleaned_data['course_name'].strip()

    def clean_course_number(self):
        return self.cleaned_data['course_number'].strip()


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

    def clean_first_name(self):
        return self.cleaned_data['first_name'].strip()

    def clean_last_name(self):
        return self.cleaned_data['last_name'].strip()

    def clean_disambiguator(self):
        if len(self.cleaned_data['disambiguator']) == 0:
            result = self.cleaned_data['disambiguator']
        else:
            result = self.cleaned_data['disambiguator'].strip()

        return result


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Registration
        fields = '__all__'


class SemesterForm(forms.ModelForm):
    class Meta:
        model = Semester
        fields = '__all__'

dhanani_ria_ezu/courseinfo/templates/courseinfo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            title is provided by inheriting templates
        {% endblock %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if IE]><script
      src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script><![endif]-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'coursinfo/normalize.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'courseinfo/skeleton.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'courseinfo/style.css' %}">
    {% block head %}{% endblock %}
</head>

<body>

<div class="container">
    <div class="status row">
        <div class="offset-by-eight four columns">
            <ul class="inline">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout_urlpattern' %}">
                        Log Out, {{ user.get_username }}</a></li>
                {% else %}
                    <li><a href="{% url 'login_urlpattern' %}">
                        Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <header class="row">
        <div class="offset-by-one ten columns">
            <h1 class="logo">EZ University</h1>
            <h2>Course Information System</h2>
        </div>
    </header>
    <nav>
        <ul>
            {% if perms.courseinfo.view_instructor %}
                <li>
                    <a href="{% url 'courseinfo_instructor_list_urlpattern' %}">
                        Instructors</a></li>
            {% endif %}

            {% if perms.courseinfo.view_section %}
                <li>
                    <a href="{% url 'courseinfo_section_list_urlpattern' %}">
                        Sections</a></li>
            {% endif %}

            {% if perms.courseinfo.view_course %}
                <li>
                    <a href="{% url 'courseinfo_course_list_urlpattern' %}">
                        Courses</a></li>
            {% endif %}

            {% if perms.courseinfo.view_semester %}
                <li>
                    <a href="{% url 'courseinfo_semester_list_urlpattern' %}">
                        Semesters</a></li>
            {% endif %}


            {% if perms.courseinfo.view_student %}
                <li>
                    <a href="{% url 'courseinfo_student_list_urlpattern' %}">
                        Students</a></li>
            {% endif %}


            {% if perms.courseinfo.view_registration %}
                <li>
                    <a href="{% url 'courseinfo_registration_list_urlpattern' %}">
                        Registrations</a></li>
            {% endif %}


            <li>
                <a href="{% url 'about_urlpattern' %}">
                    About</a></li>

        </ul>
    </nav>
    <main>
        {% block content %}
            <div class="row">
                <section class="eight columns">
                    {% block org_content %}
                        This is default content!
                    {% endblock %}
                </section>
                <section class="desktop four columns">
                    {% block create_button %}{% endblock %}
                </section>
            </div>
            <div class="row">
                <div class="twelve columns">
                    {% block content_footer %}{% endblock %}
                </div>
            </div>
        {% endblock %}
    </main>
    {% if is_paginated %}
        <div class="row">
            <div class="twelve columns">
                <ul class="pagination">
                    {% if first_page_url %}
                        <li>
                            <a href="{{ first_page_url }}">
                                First</a>
                        </li>
                    {% endif %}
                    {% if previous_page_url %}
                        <li>
                            <a href="{{ previous_page_url }}">
                                Previous</a>
                        </li>
                    {% endif %}
                    <li>
                        Page {{ page_obj.number }}
                        of {{ paginator.num_pages }}
                    </li>
                    {% if next_page_url %}
                        <li>
                            <a href="{{ next_page_url }}">
                                Next</a>
                        </li>
                    {% endif %}
                    {% if last_page_url %}
                        <li>
                            <a href="{{ last_page_url }}">
                                Last</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    {% endif %}
</div><!-- container -->

<footer>
    <p>
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
            <img alt="Creative Commons License" style="border-width:0"
                 src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"/>
        </a><br/><span property="dct:title">EZ University Tutorial Examples and Code</span>
        by
        <a href="https://www.ligent.net" property="cc:attributionName"
           rel="cc:attributionURL">Ligent, LLC</a> are licensed under a
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike
            4.0 International License</a>.
    </p>
    <p>Portions of the EZ University code are based upon code from
        <a href="https://django-unleashed.com">Django Unleashed</a>,
        <a href="http://getskeleton.com/">Skeleton</a>, and
        <a href="https://necolas.github.io/normalize.css/">Normalize.css</a> and
        are subject to the intellectual property rights restrictions of those works.
    </p>
</footer>

</body>

</html>

dhanani_ria_ezu/courseinfo/templates/courseinfo/course_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Course - {{ course }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ course }}</h2>
    <ul class="inline">
        {% if perms.courseinfo.change_course %}
        <li>
          <a
              href="{{ course.get_update_url }}"
              class="button button-primary">
            Edit Course</a></li>
        {% endif %}
        {% if perms.courseinfo.delete_course %}
        <li>
          <a
              href="{{ course.get_delete_url }}"
              class="button button-primary">
            Delete Course</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Course Number:</th>
                <td>{{ course.course_number }}</td>
            </tr>
            <tr>
                <th>Course Name:</th>
                <td>{{ course.course_name }}</td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Sections</h3>
        <ul>
            {% for section in section_list %}
                <li>
                    <a href="{{ section.get_absolute_url }}">{{ section }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no sections for this course.</em></li>
            {% endfor %}
        </ul>
    </section>
  </div></div> <!-- row -->

</article>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/course_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Course
{% endblock %}

{% block content %}
    <form
        action="{% url 'courseinfo_course_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Create Course</button>
    </form>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/instructor_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Instructor - {{ instructor }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ instructor }}</h2>
                <ul class="inline">
                    {% if perms.courseinfo.change_instructor %}
                        <li>
                            <a href="{{ instructor.get_update_url }}"
                               class="button button-primary">
                                Edit Instructor</a></li>
                    {% endif %}
                    {% if perms.courseinfo.delete_instructor %}
                        <li>
                            <a href="{{ instructor.get_delete_url }}"
                               class="button button-primary">
                                Delete Instructor</a></li>
                    {% endif %}
                </ul>

                <section>
                    <table>
                        <tr>
                            <th>First Name:</th>
                            <td>{{ instructor.first_name }}</td>
                        </tr>
                        <tr>
                            <th>Last Name:</th>
                            <td>{{ instructor.last_name }}</td>
                        </tr>
                        {% if instructor.disambiguator %}
                        <tr>
                            <th>Disambiguator:</th>
                            <td>{{ instructor.disambiguator }}</td>
                        </tr>
                        {% endif %}
                    </table>
                </section>

                <section>
                    <h3>Sections</h3>
                    <ul>
                        {% for section in section_list %}
                            <li>
                                <a href="{{ section.get_absolute_url }}">{{ section }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no sections for this instructor.</em></li>
                        {% endfor %}
                    </ul>
                </section>

            </div>
        </div> <!-- row -->

    </article>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/instructor_form_update.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Update Instructor
{% endblock %}

{% block content %}
    <form
        action="{{ instructor.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">Update Instructor</button>
    </form>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/registration_confirm_delete.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Delete Registration
{% endblock %}

{% block content %}
    <form
        action="{{ registration.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            registration {{ registration }}?
        </p>
        <a href="{{ registration.get_absolute_url }}"
            class="button button-primary">
            Cancel</a>
        <button type="submit" class="button button-primary">Delete Registration</button>
    </form>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/registration_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Registration - {{ registration }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ student }}</h2>
    <ul class="inline">
        {% if perms.courseinfo.change_registration %}
        <li>
          <a href="{{ registration.get_update_url }}"
          class="button button-primary">
            Edit Registration</a></li>
        {% endif %}
        {% if perms.courseinfo.delete_registration %}
          <a href="{{ registration.get_delete_url }}"
          class="button button-primary">
            Delete Registration</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Student:</th>
                <td><a href="{{ student.get_absolute_url }}">{{ student }}</a></td>
            </tr>
            <tr>
                <th>Section:</th>
                <td><a href="{{ section.get_absolute_url }}">{{ section }}</a></td>
            </tr>
        </table>
    </section>

  </div></div> <!-- row -->

</article>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/section_form.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Create Section
{% endblock %}

{% block content %}
    <form
        action="{% url 'courseinfo_section_create_urlpattern'%}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button button-primary">
        Create Section</button>
    </form>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/semester_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Semester - {{ semester }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ semester }}</h2>
                <ul class="inline">
                    {% if perms.courseinfo.change_semester %}
                        <li>
                            <a href="{{ semester.get_update_url }}"
                               class="button button-primary">
                                Edit Semester</a></li>
                    {% endif %}
                    {% if perms.courseinfo.delete_semester %}
                        <a href="{{ semester.get_delete_url }}"
                           class="button button-primary">
                            Delete Semester</a></li>
                    {% endif %}
                </ul>
                <section>
                    <table>
                        <tr>
                            <th>Semester Name:</th>
                            <td>{{ semester }}</td>
                        </tr>
                    </table>
                </section>

                <section>
                    <h3>Sections</h3>
                    <ul>
                        {% for section in section_list %}
                            <li>
                                <a href="{{ section.get_absolute_url }}">{{ section }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no sections for this semester.</em></li>
                        {% endfor %}
                    </ul>
                </section>

            </div>
        </div> <!-- row -->

    </article>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/student_detail.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Student - {{ student }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ student }}</h2>
    <ul class="inline">
        {% if perms.courseinfo.change_student %}
        <li>
          <a href="{{ student.get_update_url }}"
          class="button button-primary">
            Edit Student</a></li>
        {% endif %}
        {% if perms.courseinfo.delete_student %}
          <a href="{{ student.get_delete_url }}"
          class="button button-primary">
            Delete Student</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>First Name:</th>
                <td>{{ student.first_name }}</td>
            </tr>
            <tr>
                <th>Last Name:</th>
                <td>{{ student.last_name }}</td>
            </tr>
            {% if student.disambiguator %}
                <tr>
                    <th>Disambiguator:</th>
                    <td>{{ student.disambiguator }}</td>
                </tr>
            {% endif %}
        </table>
    </section>

    <section>
        <h3>Registrations</h3>
        <ul>
            {% for registration in registration_list %}
                <li>
                    <a href="{{ registration.get_absolute_url }}">{{ registration.section }}</a>
                </li>
            {% empty %}
                <li><em>This student is not currently registered for any sections.</em></li>
            {% endfor %}
        </ul>
    </section>

  </div></div> <!-- row -->

</article>
{% endblock %}

dhanani_ria_ezu/courseinfo/templates/courseinfo/student_list.html
{% extends 'courseinfo/base.html' %}

{% block title %}
    Student List
{% endblock %}

{% block create_button %}
    {% if perms.courseinfo.add_student %}
    <a
        href="{% url 'courseinfo_student_create_urlpattern'  %}"
        class="button button-primary">
      Create New Student</a>
    {% endif %}
{% endblock %}

{% block org_content %}
  <h2>Student List</h2>
    {% if perms.courseinfo.add_student %}
    <div class="mobile">
      <a
          href="{% url 'courseinfo_student_create_urlpattern' %}"
          class="button button-primary">
        Create New Student</a>
    </div>
    {% endif %}
  <ul>
    {% for student in student_list %}
      <li>
        <a href="{{ student.get_absolute_url }}">
          {{ student }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no students available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}